# Generated by Django 5.2.7 on 2025-11-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='comments',
            new_name='comment',
        ),
    ]
